### ISSUE TITLE
[Bug] TextNode hasMissingFont method does not provide an accurate answer

### ISSUE THREAD

**Issue by david-vaclavek** [figma/plugin-typings#65] opened 2021-09-14 12:07 UTC
## Problem
When tried to resolve whether there are fonts missing within `TextNode` using `hasMissingFont` property it returns `false`.
Afterwards, by setting the `characters` property on the very same `TextNode`, an exception was thrown:

```js
{
message: 'in set_characters: Cannot write to node with unloaded font "Roboto Medium". Please call figma.loadFontAsync({ family: "Roboto", style: "Medium" }) and await the returned promise first.',
}
```

## Replication (simplified)

```js
export const replicate = async () => {
  let missingFonts = [];

  const node = figma.getNodeById("I1:2004;42:1020");
  if (node.type === "TEXT") {
    if (node.hasMissingFont) { // this returns false
      missingFonts = node.getRangeAllFontNames(0, node.characters.length);

      if (missingFonts.length) {
        await Promise.all(missingFonts.map(async (font) => figma.loadFontAsync(font)));
      }
    }
    node.characters = "Updated text node"; // this throws an exception
  }
};
```

It seems like that the `hasMissingFont` property does not take into account a `fontStyle` (maybe).

Or am I missing anything?

**Comment by zyumbik** [comment] 2021-09-14 12:14
This is not a bug. `hasMissingFont` is not related to unloaded fonts. Missing fonts are the ones not available to the user, e.g. someone created a text node and this user doesn't have the font used in this text node installed on their computer. You can't load missing fonts because they are not available. 

Regarding loading fonts, all fonts are unloaded until your plugin loads them. So you can either call `loadFontAsync` every time you want to modify characters (it shouldn't put much strain on the system because once the font is loaded the first time, this function will return instantly). Or you can write all fonts that you've loaded since the plugin launch into an array, then check if the font is loaded by checking if it's in the array.

**Comment by david-vaclavek** [comment] 2021-09-14 12:22
Thank you for clarification @zyumbik.

This was really helpful as I did not really know it works the way you've just described (even though I've read [TextNode documentation](https://www.figma.com/plugin-docs/api/TextNode/).

I was thinking about storing the loaded fonts in an array like you've just said. But if you say that `loadFontAsync` does not load a font couple times (that means provides check if the font was loaded and just returns if so), I think that would be an unnecessary extra work.

If you don't have anything to add, you can close the issue report.
Thank you.

**Comment by zyumbik** [comment] 2021-09-15 21:29
No problem David, happy to help!

Can someone from Figma close this? @minigolf2000?

**Comment by johndoherty** [comment] 2021-09-17 18:10
Thanks @zyumbik for the really clear explanation. @david-vaclavek we'll try to update our documation to make this distinction clearer. Closing this issue.

**Closed by johndoherty** 2021-09-17 18:10 UTC
